### PR TITLE
correct return value for jaro_distance spec

### PR DESCRIPTION
**Pull request by eksperimental**
based on the discussion https://github.com/elixir-lang/elixir/pull/3112#discussion-diff-42950249

### CODE REVIEW

**Comment by lexmag** [comment]
`Gettext.Fuzzy.matcher/1` needs correction also.

**Comment by eksperimental** [comment]
done ;-D

**Comment by whatyouhide** [comment]
Thanks @eksperimental, great find :)

**Comment by eksperimental** [comment]
@lexmag did it :-P

**Comment by eksperimental** [comment]
correction, that was teamwork! haha

**Comment by whatyouhide** [comment]
Right, thanks to both you and @lexmag then :)

**Pull request merged**
