### PR TITLE
Comments support

### PR DESCRIPTION
**Pull request by whatyouhide**
Hey there, I quickly added support for tokenizing and parsing comments as per #16. I'm opening the PR so that you're all notified but I'm merging it right away since the code is very simple. If you have any comments or feedback I still would appreciate it a lot, and we can change the code later if necessary :). Thanks!

### CODE REVIEW

**Comment by josevalim** [comment]
This looks great! I have a suggestion for you to keep in mind. You don't need to change anything but it may be handy in the future.

One option is to keep the `:comments` entry as a list of binaries and store the reference directly in the translation? Why? Because it will make easier to match on the reference later and it will also make it easier to dump the comments back.

So instead of having:

    comments: [{:translator, "Hello"}, {:reference: "lib/foo.ex:23"}]

I would have:

    comments: ["# Hello", "#: lib/foo.ex"], reference: {"lib/foo.ex", 23}

I guess we could have multiple references too... so it may need to be:

    comments: [...], references: [{"lib/foo.ex", 23}]

If that is the case, then we don't have large benefits compared to the current approach. In any case, it is worth discussing. :)

**Comment by whatyouhide** [comment]
Thanks for the feedback! So, the first idea of storing `:reference` in the translation could be very nice:

> `comments: ["# Hello", "#: lib/foo.ex"], reference: {"lib/foo.ex", 23}`

The main problem I see with it is that we're pretty much *sure* that there will be some translations with more than on reference, which brings us to the second suggestion:

> `comments: [...], references: [{"lib/foo.ex", 23}]`

This is nice (maybe nice than the solution I implemented), but I can see one main downside: what if we add flag comments or other comment types? This solution isn't "scalable" in that sense, right?

Your solution has the advantage of being easier to dump back (which is not very hard to do even with a `Keyword.t` list of comments) and of being pattern-matchable.

For now I went with a simple kw list because, well, it's simple :stuck_out_tongue: and it allows us to keep the order of comments but at the same time retrieve all comments of a given type (`Keyword.get_values/2`).

So, what do you think?

**Comment by josevalim** [comment]
Right, the biggest downside of the current approach is that dumping needs to know about the existing comment types. So, in this sense, both aren't "scalable" because once we add a new comment type, like flag, we would need to teach the dumper how to dump it too.

**Comment by whatyouhide** [comment]
Yes, that is true but we wouldn't need to change the `(Plural)Translation` structs in to add a `:flags` field and whatnot. Not modifying the structs in this way would make, e.g., adding a flag very uncomfortable I think. I keep mentioning flags comments because even if we're not implementing them for now, we could need them in order to mark translations as "fuzzy" at some point, which would mean adding a *fuzzy* comment type and you see where this is going :).

**Comment by josevalim** [comment]
Yes, I get it. :) Alternatively, someone would just extract the flag from the comments too, it should not be hard:

    flags = for <<"#&", rest::binary>> <- translation.comments, do: rest

It is up to you!

**Comment by whatyouhide** [comment]
We could provide functions like that ourselves if we need to, but I think users would rarely need to use them. Anyways, let's go with your solution for now, we can always change it later if we'll need to :)

**Pull request merged**
