### PR TITLE
Handle unknown locales in Gettext.Plural

### PR DESCRIPTION
**Pull request by whatyouhide**
Implements what was discussed in #87. @josevalim let me know what you think, but it should be straightforward :)

/cc @maufl

### CODE REVIEW

**Comment by maufl** [comment]
Looks good to me, except that it will not handle locales separated by a dash right?

**Comment by whatyouhide** [comment]
@maufl nope, as I'm not sure that's a common use case. You can fix this by hand extremely easily anyways by creating a new pluralizer module.

**Comment by maufl** [comment]
Are you sure? Because it seems that this is the format used in accept language headers.

But of course it would work for me too :)

**Comment by josevalim** [comment]
@maufl in this case it likely makes sense to convert to underscore before passing to gettext. :)

**Comment by whatyouhide** [comment]
@maufl has a point though:

* underscores are fine: https://en.wikipedia.org/wiki/Locale
* dashes too: https://en.wikipedia.org/wiki/IETF_language_tag

not sure we should support both. I'd of course prefer to support just underscores as the implementation is cleaner, stricter and less error-prone, but I'm not convinced.

**Comment by josevalim** [comment]
Yes, I'd go with one format anyway otherwise you end-up having inconsistent locale folders between projects. Imagine having to set "pt_BR" in one backend and "pt-BR" in another locale backend.

**Comment by whatyouhide** [comment]
Let's go with only underscores then, I'll updated the docs and then merge this.

**Comment by whatyouhide** [comment]
@josevalim updated the PR with docs and a new exception, `Gettext.Plural.UnknownLocaleError`, that can be raised when a pluralized module doesn't know how to handle a locale:

```elixir
raise Gettext.Plural.UnknownLocaleError, "no-nb"
```

would love a quick review before merging (of course, @lexmag can pitch in if he wants :smiley:).

@maufl by the way, implementing a custom pluralizer module that handles dashes should be straightforward and a very elegant solution IMO :)

```elixir
defmodule DashPluralized do
  @behaviour Gettext.Plural

  def nplurals(locale) do
    locale
    |> String.split("-", parts: 2, trim: true)
    |> hd()
    |> Gettext.Plural.nplurals()
  end

  def plural(locale, n) do
    # pretty much the same thing
  end
end
```

**Comment by josevalim** [comment]
It looks great. I still wouldn't suggest a custom pluralizer for handling the dashes because it would still mean you would need to have no_OT and no-OT in the filesystem, no?

**Comment by whatyouhide** [comment]
@josevalim oh, good point. I keep forgetting that pluralizing and translating are two different things :) but for @maufl's use case, if he only uses `no-OT`, then `DashPluralizer` would still be a good fit IMO.

I updated the docs so that they don't mention anything about implementing a forwarding pluralizer :)

**Comment by maufl** [comment]
I don't understand why I would need to have folders with dashes and underscores, but thank you very much for the code snippet @whatyouhide :) I'll add that to our code base next week.

**Comment by whatyouhide** [comment]
@maufl if you want to support both `no_OT` and `no-OT`, you'd have to have translations in both the `no_OT` as well as the `no-OT

**Comment by maufl** [comment]
Ok, I did not even assume that anybody would do something like that, without normalizing it in the application itself ...

**Pull request merged**
